# Configuración simplificada para Render
services:
  - type: web
    name: whatsapp-chatbot
    env: python
    region: ohio
    plan: starter
    
    # Health check
    healthCheckPath: /health
    
    # Environment variables
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # Set manually in dashboard
        
      - key: ENVIRONMENT
        value: production
        
      - key: LOG_LEVEL
        value: INFO
        
      - key: WHATSAPP_HEADLESS
        value: true
        
      - key: DEBUG
        value: false
        
      # Rate limiting para producción
      - key: RATE_LIMIT_PER_USER
        value: 20
        
      - key: RATE_LIMIT_WINDOW
        value: 60
        
      # Memory management
      - key: MAX_CONTEXT_TOKENS
        value: 6000
        
      - key: MAX_MEMORY_MESSAGES
        value: 20
        
      # Department emails (configurar según empresa)
      - key: SALES_EMAIL
        value: ventas@empresa.com
        
      - key: SUPPORT_EMAIL
        value: soporte@empresa.com
        
      - key: BILLING_EMAIL
        value: facturacion@empresa.com
        
      - key: GENERAL_EMAIL
        value: info@empresa.com
        
      - key: COMPLAINT_EMAIL
        value: gerencia@empresa.com
        
      - key: INFORMATION_EMAIL
        value: info@empresa.com
        
      # Redis connection from addon
      - key: REDIS_URL
        fromDatabase:
          name: whatsapp-redis
          property: connectionString

# Redis database
databases:
  - name: whatsapp-redis
    databaseName: whatsapp_chatbot
    user: whatsapp_user
    plan: starter
    region: ohio